maxmtu: '9216'
outdir: /data/scaleCalibration
preset: faster
quality: 17
site: SCALECALIB
storagethreads: 1
fps: 10
storeallframes: False
newfileinterval: 0
liveratio: 2
camera:
- name: visss_trigger
  follower: False
  interface: enp35s0f0
  ip: 192.168.100.2
  mac: 00:01:0D:C3:0F:34
  teledyneparameters:
    TestImageSelector: Off
    fastReadoutMode: Off
    ExposureMode: Timed
    ExposureTime: 400
    GainSelector: SensorAnalog
    Gain: 1
    BlackLevelRaw: 1
    TriggerMode: Off
    AcquisitionFrameRate: 10
    IO:
    - LineSelector: Line3
      outputLineSource: Off
    - LineSelector: Line4
      outputLineSource: Off
    sensorFpnCorrectionMode: Off
- name: visss_follower
  follower: True
  interface: enp35s0f1
  ip: 192.168.200.2
  mac: 00:01:0D:C3:04:9F
  teledyneparameters:
    TestImageSelector: Off
    fastReadoutMode: Off
    ExposureMode: Timed
    ExposureTime: 400
    GainSelector: SensorAnalog
    Gain: 1
    BlackLevelRaw: 1
    TriggerMode: Off
    AcquisitionFrameRate: 10
    IO:
    - LineSelector: Line3
      outputLineSource: Off
    - LineSelector: Line4
      outputLineSource: Off
    sensorFpnCorrectionMode: Off
externalTrigger: []